# These are supported funding model platforms

github: hero-org # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
custom: ['https://hypersub.withfabric.xyz/collection/herocast-hyper-club-1w4xx8vap9ngg?referrer=0xd203Da829d26FEDB6F861913a1e05a054794E509', 'https://zora.co/collect/base:0x1b3aa44867b1daf0bd8b31f7bc638e28211579b9/premint-1'] 
# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
