/// <reference types="vite/client" />

// Minimal ambient type for the workerd virtual module. The full typed binding is
// generated by `wrangler types` (worker-configuration.d.ts, gitignored); this keeps
// `tsc` green without that step and without pulling all of @cloudflare/workers-types.
declare module 'cloudflare:workers' {
  export const env: Record<string, string | undefined>;
}

// Vite-inlined client env (browser Supabase client; see src/lib/supabase/client.ts).
interface ImportMetaEnv {
  readonly VITE_SUPABASE_URL?: string;
  readonly VITE_SUPABASE_ANON_KEY?: string;
}
interface ImportMeta {
  readonly env: ImportMetaEnv;
}
