#!/bin/sh

if command -v pnpm >/dev/null 2>&1; then
  PNPM_CMD="pnpm"
elif [ -f "$HOME/.local/share/pnpm/pnpm" ]; then
  PNPM_CMD="$HOME/.local/share/pnpm/pnpm"
elif [ -f "/opt/homebrew/bin/pnpm" ]; then
  PNPM_CMD="/opt/homebrew/bin/pnpm"
elif [ -f "/usr/local/bin/pnpm" ]; then
  PNPM_CMD="/usr/local/bin/pnpm"
else
  PNPM_CMD="npx pnpm"
fi

$PNPM_CMD exec lint-staged
