name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published] # has GITHUB_REF as refs/tags/<tag_name>

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run checks
        run: pnpm check

      - name: Sentry Release
        if: github.ref == 'refs/heads/main'
        uses: getsentry/action-release@v1.7.0
        with:
          ignore_missing: true
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
